[project]
name = "dglab-kit-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LF112", email = "lf@lf112.net" }
]
requires-python = ">=3.13"
dependencies = [
    "websockets>=15.0.1",
]

[build-system]
requires = ["uv_build>=0.9.1,<0.10.0"]
build-backend = "uv_build"
